[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Categories"
  url = "/category/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -107
[[main]]
  parent = "Links"
  name = "About"
  url = "/about/"
[[main]]
  parent = "Links"
  name = "Contact me"
  url = "mailto:ting911111@gmail.com"

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/chiehting"
[[social]]
  name = "linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/chiehting-lee-787130126/"
[[social]]
  name = "telegram"
  weight = 3
  url = "https://t.me/chiehting"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"